AWSTemplateFormatVersion: '2010-09-09'
Description: This template creates a Lambda function that will ingest a CloudWatch Event, and delete the referenced IGW attachment from the VPC.
             By default it is set to a read-only action, but can be changed once deployed to actually execute the delete. Use with caution, 
             this is not production level code and is used to illustrate a possible scenario for a workshop.
Parameters:
  FunctionName:
    Type: String
    Description: Name of the lambda function.
    Default: DeleteIGWAttachLambdaCWE
    AllowedPattern: ^.*[^0-9]$
    ConstraintDescription: Must end with non numberic character.
Outputs:
  LambdaRoleARN:
    Description: Role for Lambda execution.
    Value:
      Fn::GetAtt:
        - LambdaRole
        - Arn
    Export:
      Name:
        Fn::Sub: LambdaRole
  LambdaFunctionName:
    Value:
      Ref: LambdaFunction
  LambdaFunctionARN:
    Description: Lambda function ARN.
    Value:
      Fn::GetAtt:
        - LambdaFunction
        - Arn
    Export:
      Name:
        Fn::Sub: LambdaARN-${FunctionName}
Resources:
  LambdaRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName:
        Fn::Sub: lambda-role
      AssumeRolePolicyDocument:
        Statement:
          - Action:
            - sts:AssumeRole
            Effect: Allow
            Principal:
              Service:
              - lambda.amazonaws.com
        Version: 2012-10-17
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AWSLambdaExecute
      Policies:
        - 
            PolicyName: "Allow-Lambda-Delete-IGW-Attach"
            PolicyDocument:
                Version: "2012-10-17"
                Statement:
                    -
                        Effect: "Allow"
                        Action: 
                            - "ec2:DetachInternetGateway"
                        Resource: "*"
      Path: /
  LambdaFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: !Ref FunctionName
      Description: Lambda function to demo detaching IGW on CWE
      Runtime: python3.7
      Code:
        S3Bucket: reinforce2019-grc333-session
        S3Key: lambda_delete_igw_attach.zip
      Handler: lambda_delete_igw_attach.lambda_handler
      MemorySize: 128
      Timeout: 10
      Role:
        Fn::GetAtt:
          - LambdaRole
          - Arn